name: LCCore
version: '${version}'
main: lc.core.LCCore
depend:
  - PlaceholderAPI
commands:
  vippoints:
    description: Ver VipPoints de tu cuenta
  lcoins:
    description: Ver LCoins en tu cuenta
  minelc:
    description: Recargar datos de los jugadores desde la base de datos.